version: 2

project_name: chainenv

before:
  hooks:
    - go mod tidy

builds:
  - id: chainenv
    main: .
    binary: chainenv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -buildid=
      - -X github.com/dvcrn/chainenv/cmd.version={{.Version}}
    overrides:
      - goos: darwin
        env:
          - CGO_ENABLED=1

release:
  extra_files:
    - glob: "./bottles/*.tar.gz"
  replace_existing_artifacts: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files: []

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
