name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v4
      #   with:
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Create and Upload Bottle
        run: |
          brew tap dvcrn/homebrew-formulas
          brew update
          brew install --build-bottle chainenv
          brew bottle chainenv
          
          mkdir -p bottles
          
          for f in chainenv--*.tar.gz; do
              mv "$f" "bottles/${f//--/-}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
