name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Homebrew Bottle
        run: |
          # Install the released binary
          BINARY_PATH=$(find dist -name 'chainenv_darwin_amd64_v1/chainenv' -o -name 'chainenv_darwin_arm64_v1/chainenv' | head -n 1)
          sudo cp "$BINARY_PATH" /usr/local/bin/chainenv
          sudo chmod +x /usr/local/bin/chainenv

          # Create bottle
          brew install --build-bottle chainenv
          brew bottle chainenv

          # Upload the bottle as an artifact
          mkdir -p bottles
          mv chainenv--*.tar.gz bottles/

      - name: Upload Bottle
        uses: actions/upload-artifact@v3
        with:
          name: homebrew-bottle
          path: bottles/*.tar.gz
