name: Build Release Assets

on:
  push:
    tags:
      - "*"

jobs:
  build-bottles:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-14, macos-15]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottle
        run: |
          brew tap dvcrn/homebrew-formulas
          brew install --build-bottle --verbose chainenv
          brew bottle chainenv

      - name: Upload bottle
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: ./*.bottle*.tar.gz

  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          OUTPUT="chainenv-${{ matrix.goos }}-${{ matrix.goarch }}"
          go build -ldflags="-s -w" -o "${OUTPUT}" main.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: chainenv-*
